language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: c15UDFL9Y7GIenKZtZ/LeUYLTLr1nT31LrJntXarj1sR4pb7QlLLOI7ayldru210xjSydG11lyEYjEVKYcQyKSL2pzvYWVBQQAoLTlz76JTgq48KCtMOEth9aDtyZlMcjVII+FWrDIqKORt3zOMIIrSzySHb60CqPtqa+2QBZHGanz7ysEBjjOhyNUbc1GxxrI/F9NC4tB3ZvRGfBcD6a6dlzwZqPoMXjVxb7XIn3ux9lO79l8mOutrw9mhXlaLyxjyHTPWpfmj2Poc12WwLbiuOIGyZQlFjn4wRgf4AlvgZV+dbXbmMB1t7UgKMvLoysMiyCQ6ufStpKBuUXw8d6CwGCG28j+3cs01Q0w93ESf2EvxrkOni8i1OJWhquaLrXbU0N4nkOAAEgovpFAUOM6fOq8cgTs1RZ9mUEcgVGDs0d+F86K4H0O4SmetIIXMpaGsgnMqROEvPiebBGfmfEi4n0qs07LYDlItfRs/ACSGg6SXhwYzNHC1HJzYoCSoIX+axaXmJBMijMbJFjz/5yTMFOrDLa1Q1Z1wHC3qAt9lVPMDCfhUBsaDyeZoIPkDwP0JxWfcPVVgk+sLSSzEvIPFCjgOPriVtnpnzdZnV/zfRitqHyI12yhmJL4J+j/GqoktWx+/ep9CCJr7APRp4tVAbrhaH8JRTH6+AY5+v5c8=
  app: fierce-hollows-75247
  on:
    repo: csierra15/budgetr
